# Generated by Django 5.0 on 2024-01-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_options_chatgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
