# Generated by Django 5.0 on 2024-01-11 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='group',
        ),
    ]
